# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Define Environment Variable WORKSPACE
          command: |
            echo 'export WORKSPACE=$CIRCLE_WORKING_DIRECTORY' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: install-grunt
          command: 'sudo npm install -g grunt'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # run build
      - run: 
          name: Build MTA and Deploy
          command: |
            bash -ex build.sh

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - store_artifacts:
          path: ~/repo/dist